### ISSUE TITLE
(Staging) Exception when updating C2DNS Domain when fields are changed

### ISSUE THREAD

**Issue by deadbits** [InQuest/ThreatKB#194]
After updating an existing DNS artifact and saving, exception below is thrown:
The domain name itself is still updated and saved. This happens regardless of what field is changed.

```
ERROR in error_handling [/opt/ThreatKB/app/routes/error_handling.py:18]:
'NoneType' object has no attribute 'id'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/ThreatKB/flask/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/ThreatKB/flask/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/ThreatKB/flask/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/ThreatKB/app/routes/c2dns.py", line 205, in update_c2dns
    db.session.add(MetadataMapping(value=value_dict["value"], metadata_id=m.id, artifact_id=entity.id,
AttributeError: 'NoneType' object has no attribute 'id'
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/opt/ThreatKB/flask/local/lib/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/ThreatKB/flask/local/lib/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/ThreatKB/flask/local/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/ThreatKB/app/routes/c2dns.py", line 205, in update_c2dns
    db.session.add(MetadataMapping(value=value_dict["value"], metadata_id=m.id, artifact_id=entity.id,
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by dcuellar322** [comment]
@deadbits I'm not able to reproduce this.

I think it may be bad data related.

![image](https://user-images.githubusercontent.com/3661852/36637304-224694f6-199f-11e8-92a5-8bb1d193215e.png)

Line 205 is throwing an exception because it's trying to get the ID of M and M is null.

The only way that block of data gets hit is when metadata_values are being passed and they don't have a corresponding value in the Metadata table.

If this is getting done via REST call, then that's probably whats happening. You can not pass a key/value pair unless the key is defined in the Metadata table. If it's not, then that would yield the exception to be raised.

If it's intended to create the Metadata key if it doesn't exist then I would need to know.

**Comment by deadbits** [comment]
So in this case my initial bug triggered on an already created C2DNS Artifact that, when I went back to update, caused this error. If it's a Metadata key not existing - would the error not be triggered on the initial creation of the Artifact?

**Comment by deadbits** [comment]
Thanks for the feedback, btw. Do you have any suggested steps on how I could check to see if the key is defined in the metadata table? Unfortunately the local instance I was tested this on is now pretty badly broken and I can't actually load the web UI anymore (my fault here) - could I check the DB to see if it exists?

**Comment by dcuellar322** [comment]
I was finally able to reproduce this, I'll go ahead and fix it.

**Comment by dcuellar322** [comment]
Fixed. Please verify after Pull Request is raised and closed.
