### ISSUE TITLE
(Staging) Release notes incorrectly display metadata values

### ISSUE THREAD

**Issue by deadbits** [InQuest/ThreatKB#200]
After creating a Release and exporting the Release Notes text file, the metadata values do not actually show the Yara signatures true metadata values - instead they display the values assigned by Metadata's mappings:
    - `Confidence`, `Severity`, and `Description` are incorrect
    - `EventID`, `Name`, and `Category` **are** correct

**Examples from exported Release notes:**
```
EventID: 1000008
Name: FID_Java_Archive
Category: FileID
Confidence: confidence
Severity: severity
Description: description

EventID: 1000007
Name: FID_ELF_Binary
Category: FileID
Confidence: confidence
Severity: severity
Description: description
```

**Comment by dcuellar322** [comment]
Fixed. Please verify after Pull Request is raised and closed.

Problem with this one was that Confidence, Severity and Description are no longer columns and they weren't cleaned up from this code. That's why they are still being added with default values of "confidence", "severity", and "description".

New version I pushed only displays EventID, Name and Category now.
