### ISSUE TITLE
Next Review On parsing date incorrectly

### ISSUE THREAD

**Issue by needmorecowbell** [InQuest/ThreatKB#366]
![image](https://user-images.githubusercontent.com/7833164/68145385-a9302400-ff03-11e9-8a8a-00356fd133de.png)

Then I save the change using ctrl+s...

And when I go back into the edit panel to see the date has been saved: 
![image](https://user-images.githubusercontent.com/7833164/68145513-f4e2cd80-ff03-11e9-9528-2e787d1cdbac.png)

The date has been changed. This seems to be a parsing issue between what is received from the calendar popup and what is entered on save.

---

C2IP record being shown has the URL of: https://threatkb.inquest.net/#!/c2ips/238245

**Comment by needmorecowbell** [comment]
Seems to be happening on write to the database: 

![image](https://user-images.githubusercontent.com/7833164/68145703-615dcc80-ff04-11e9-8d59-2d3556f0a448.png)

**Comment by ofzza** [comment]
@danny248 
I've looked into this and this is how the value is returned by the API:
![image](https://user-images.githubusercontent.com/4250750/68342740-882a2780-00eb-11ea-8d80-fbe8198d2d5d.png)

It is obviously formatted differently than any other date in the response. Is this something we could change on the API side, especially since the DB screen-shot above seems to be showing the value normally formatted int he DB?
