### ISSUE TITLE
bug: fix the signature testing

### ISSUE THREAD

**Issue by pedramamini** [InQuest/ThreatKB#90]
![image](https://user-images.githubusercontent.com/1253573/31640082-e10f8c0e-b2a1-11e7-8d57-46ffa72c49a2.png)

**Comment by dcuellar322** [comment]
@pedramamini @danny248 This is identical bug to #72 , and got fixed in #76 

Need to re-run the SQL migration for CFG Settings.

ffea56d3fc3f, default cfg_settings

Probably be better to to just insert the record into the cfg_settings table directly.

Put whatever default file store path you want.
`insert into cfg_settings (`key`, date_created, date_modified, public, value)
VALUES ('FILE_STORE_PATH', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 0, '/usr/local/ThreatKB/');
`

**Comment by dcuellar322** [comment]
Added exception handling and user friendly error when config setting is not set.
